# Generated by Django 3.2.7 on 2021-09-14 17:41

import audiorecord.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiorecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audiorecord.commentonaudio')),
            ],
            options={
                'verbose_name_plural': 'Audio Comment',
            },
        ),
        migrations.CreateModel(
            name='AudioTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=audiorecord.models.audio_folder_upload)),
                ('type_of_audio', models.CharField(blank=True, max_length=200, null=True)),
                ('likes_on_audio', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('comments_on_audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audiorecord.commentonaudio')),
            ],
            options={
                'verbose_name_plural': 'Audio Table',
            },
        ),
    ]
