# Generated by Django 3.2.7 on 2021-09-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiorecord', '0002_audiotable_commentonaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotable',
            name='type_of_audio',
            field=models.CharField(choices=[('SHAYARI', 'shayari'), ('MIMICKRY', 'mimickry'), ('JOKE', 'joke'), ('OTHERS', 'others')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
