# Generated by Django 3.2.7 on 2021-09-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiorecord', '0003_alter_audiotable_type_of_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotable',
            name='comments_on_audio',
        ),
        migrations.AddField(
            model_name='audiotable',
            name='comments_on_audio',
            field=models.ManyToManyField(blank=True, null=True, to='audiorecord.CommentOnAudio'),
        ),
        migrations.RemoveField(
            model_name='commentonaudio',
            name='comment_tree',
        ),
        migrations.AddField(
            model_name='commentonaudio',
            name='comment_tree',
            field=models.ManyToManyField(blank=True, null=True, related_name='_audiorecord_commentonaudio_comment_tree_+', to='audiorecord.CommentOnAudio'),
        ),
    ]
